# Generated by Django 5.0.1 on 2024-01-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_appointmentsmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentsmodel",
            name="field2",
            field=models.IntegerField(default=0),
        ),
    ]
