# Generated by Django 5.0.1 on 2024-01-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_appointmentsmodel_field2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_ID",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("CNP", models.CharField(blank=True, max_length=13, null=True)),
                ("DOB", models.DateTimeField(blank=True, null=True)),
                ("phone_no", models.CharField(blank=True, max_length=10, null=True)),
                ("e_name", models.CharField(blank=True, max_length=50, null=True)),
                ("e_surname", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("medic", "Medic"),
                            ("guard", "Guard"),
                            ("nurse", "Nurse"),
                            ("administrator", "Administrator"),
                            ("janitor", "Janitor"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("DOE", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
